<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimaalaEmployeeExam {
    
    
    public partial class ViewSwitcher {
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DimaalaEmployeeExam {
    
    
    public partial class ViewSwitcher {
    }
}
>>>>>>> d9edb163f34e7ebe1b02368a03f49843a7340363
